<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-10-16 at 16:04:38.
 */
class WSDLInterpreterTest extends PHPUnit_Framework_TestCase {

    /**
     * @var WSDLInterpreter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new WSDLInterpreter('TestWSDLFile.wsdl');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers WSDLInterpreter::savePHP
     * @todo   Implement testSavePHP().
     */
    public function testSavePHP() {
        $this->object->savePHP(__DIR__.'/');
    }

}
